post:
  operationId: createLanguageConfig
  description: Save languages that will be used for analyzers
  tags:
    - config
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/languageConfig.yaml'
  responses:
    '200':
      description: Language support has been added.
      content:
        application/json:
          schema:
            $ref: '../../schemas/languageConfig.yaml'
    '422':
      $ref: '../../responses/unprocessableEntityResponse.yaml'
get:
  operationId: getAllLanguageConfigs
  description: Get all supported languages
  tags:
    - config
  responses:
    '200':
      description: All supported languages
      content:
        application/json:
          schema:
            $ref: '../../schemas/languageConfigs.yaml'
