type: string
description: The feature name.
enum:
  - search.all.fields
  - browse.cn.intermediate.values
  - browse.cn.intermediate.remove.duplicates
  - browse.classifications
  - browse.call-numbers
